services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspaces/app
    volumes:
      - .:/workspaces/app:cached
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
